# Aashir Shukla, 917460238

all: useVelocity.o Velocity.o 
	g++ -Wall -o useVelocity useVelocity.o Velocity.o 

useVelocity.o: 
	g++ -c useVelocity.cpp 

Velocity.o: 
	g++ -c Velocity.cpp 

clean: 
	rm *.o useVelocity